"""Init

Revision ID: 121bbe9e05ce
Revises: 95df1b7b24f4
Create Date: 2026-02-04 11:33:58.077184

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import dbqueue_poc.models


# revision identifiers, used by Alembic.
revision = '121bbe9e05ce'
down_revision = '95df1b7b24f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_groups',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('last_processed_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('lock_expires_at', dbqueue_poc.models.NaiveDateTime(), nullable=True),
    sa.Column('lock_token', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('lock_owner', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_groups'))
    )
    with op.batch_alter_table('placement_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_groups_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_groups_status'))

    op.drop_table('placement_groups')
    # ### end Alembic commands ###
