"""Init

Revision ID: 37264ab45101
Revises: f5672f7ca2a6
Create Date: 2026-02-02 14:47:24.114956

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import dbqueue_poc.models


# revision identifiers, used by Alembic.
revision = '37264ab45101'
down_revision = 'f5672f7ca2a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_token', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('lock_token')

    # ### end Alembic commands ###
