"""Init

Revision ID: 7f718179e7b3
Revises: 
Create Date: 2026-02-16 11:15:06.527447

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import dbqueue_poc.models


# revision identifiers, used by Alembic.
revision = '7f718179e7b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recorded_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('placement_groups',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('last_processed_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('lock_expires_at', dbqueue_poc.models.NaiveDateTime(), nullable=True),
    sa.Column('lock_token', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('lock_owner', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_groups'))
    )
    with op.batch_alter_table('placement_groups', schema=None) as batch_op:
        batch_op.create_index('ix_placement_groups_pipeline_fetch_q', [sa.literal_column('last_processed_at ASC'), 'id'], unique=False, postgresql_where=sa.text("(status NOT IN ('TERMINATED'))"), sqlite_where=sa.text("(status NOT IN ('TERMINATED'))"))
        batch_op.create_index(batch_op.f('ix_placement_groups_status'), ['status'], unique=False)

    op.create_table('runs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('last_processed_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('lock_expires_at', dbqueue_poc.models.NaiveDateTime(), nullable=True),
    sa.Column('lock_token', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('lock_owner', sa.String(length=100), nullable=True),
    sa.Column('run_spec', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_pipeline_fetch_q', [sa.literal_column('priority DESC'), sa.literal_column('last_processed_at ASC'), 'id'], unique=False, postgresql_where=sa.text("(status NOT IN ('TERMINATED', 'FAILED', 'DONE'))"), sqlite_where=sa.text("(status NOT IN ('TERMINATED', 'FAILED', 'DONE'))"))
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('run_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('submitted_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('last_processed_at', dbqueue_poc.models.NaiveDateTime(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('lock_expires_at', dbqueue_poc.models.NaiveDateTime(), nullable=True),
    sa.Column('lock_token', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('lock_owner', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_jobs_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_pipeline_fetch_q', [sa.literal_column('priority DESC'), sa.literal_column('last_processed_at ASC'), 'id'], unique=False, postgresql_where=sa.text("(status NOT IN ('TERMINATED', 'ABORTED', 'FAILED', 'DONE'))"), sqlite_where=sa.text("(status NOT IN ('TERMINATED', 'ABORTED', 'FAILED', 'DONE'))"))
        batch_op.create_index(batch_op.f('ix_jobs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_run_id'))
        batch_op.drop_index('ix_jobs_pipeline_fetch_q', postgresql_where=sa.text("(status NOT IN ('TERMINATED', 'ABORTED', 'FAILED', 'DONE'))"), sqlite_where=sa.text("(status NOT IN ('TERMINATED', 'ABORTED', 'FAILED', 'DONE'))"))

    op.drop_table('jobs')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index('ix_runs_pipeline_fetch_q', postgresql_where=sa.text("(status NOT IN ('TERMINATED', 'FAILED', 'DONE'))"), sqlite_where=sa.text("(status NOT IN ('TERMINATED', 'FAILED', 'DONE'))"))

    op.drop_table('runs')
    with op.batch_alter_table('placement_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_groups_status'))
        batch_op.drop_index('ix_placement_groups_pipeline_fetch_q', postgresql_where=sa.text("(status NOT IN ('TERMINATED'))"), sqlite_where=sa.text("(status NOT IN ('TERMINATED'))"))

    op.drop_table('placement_groups')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_recorded_at'))

    op.drop_table('events')
    # ### end Alembic commands ###
