"""Init

Revision ID: 95df1b7b24f4
Revises: 37264ab45101
Create Date: 2026-02-03 13:51:51.852583

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

import dbqueue_poc.models


# revision identifiers, used by Alembic.
revision = '95df1b7b24f4'
down_revision = '37264ab45101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_expires_at', dbqueue_poc.models.NaiveDateTime(), nullable=True))
        batch_op.add_column(sa.Column('lock_token', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
        batch_op.add_column(sa.Column('lock_owner', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_owner', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('lock_owner')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('lock_owner')
        batch_op.drop_column('lock_token')
        batch_op.drop_column('lock_expires_at')

    # ### end Alembic commands ###
